language: python
python:
    - "2.7"
install: make init
script:
    python -m pip install --upgrade pip
    pip install -r requirements.txt
git:
    depth: 3
branches:
    only:
    - master
    - develop
notifications:
    slack: studiarbeit-jarpis:1hZhWcJYccrmsc3UtS7J07aE
