language: python
python:
    - "2.7"
before_install:
    - pip install --upgrade pip
install:
    - make init
script:
    - make test
git:
    depth: 3
branches:
    only:
    - master
    - develop
notifications:
    slack: studiarbeit-jarpis:1hZhWcJYccrmsc3UtS7J07aE
